# Adding sudo:required such that Travis doesn't use containers; otherwise
# Bazel's sandbox execution will fail. The alternative is to disable Bazel's
# sandbox execution using "--genrule_strategy=standalone",
# "--spawn_strategy=standalone" and --test_strategy=standalone.
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - wget
      # Package list from http://bazel.io/docs/install.html
      - oracle-java8-installer
      - pkg-config
      - zip
      - zlib1g-dev

install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.3.0/bazel-0.3.0-installer-linux-x86_64.sh' -O ./bazel-installer.sh
  - chmod +x ./bazel-installer.sh
  - ./bazel-installer.sh  --user

script:
  - script/setup
  - bazel test :all --test_output=errors
