
licenses(["notice"])

cc_library(
    name = "public_headers",
    hdrs = [
         "aggregator_options.h",
         "service_control_client.h",
         "transport.h",
    ],
    visibility = ["//visibility:public"],
)

