// TODO: Insert description here. (generated by jaebong)

#include <src/quota_aggregator_impl.h>

#include <unordered_map>

#include "google/api/metric.pb.h"
#include "google/api/servicecontrol/v1/metric_value.pb.h"
#include "google/api/servicecontrol/v1/operation.pb.h"
#include "utils/google_macros.h"

namespace google {
namespace service_control_client {
namespace {

TEST(QuotaAggregatorImpl, Test1) {
  // TODO(jaebong): Auto-generated test stub
}

}  // namespace
}  // namespace service_control_client
}  // namespace google
